class Constants:
    # DR_Net
    DRNET_EPOCHS = 75
    DRNET_SS_EPOCHS = 1
    DRNET_LR = 1e-4
    DRNET_LAMBDA = 0.0001
    DRNET_BATCH_SIZE = 64
    DRNET_INPUT_NODES = 17
    DRNET_SHARED_NODES = 200
    DRNET_OUTPUT_NODES = 100
    ALPHA = 1
    BETA = 1
