class Constants:
    # DR_Net
    DRNET_EPOCHS = 75
    DRNET_SS_EPOCHS = 1
    DRNET_LR = 5e-3
    DRNET_LAMBDA = 0.001
    DRNET_BATCH_SIZE = 100
    DRNET_INPUT_NODES = 25
    DRNET_SHARED_NODES = 200
    DRNET_OUTPUT_NODES = 100
    ALPHA = 1
    BETA = 1
